// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	context "context"

	github "github.com/google/go-github/v32/github"
	mock "github.com/stretchr/testify/mock"
)

// OrganizationsService is an autogenerated mock type for the OrganizationsService type
type OrganizationsService struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, user, opts
func (_m *OrganizationsService) List(ctx context.Context, user string, opts *github.ListOptions) ([]*github.Organization, *github.Response, error) {
	ret := _m.Called(ctx, user, opts)

	var r0 []*github.Organization
	if rf, ok := ret.Get(0).(func(context.Context, string, *github.ListOptions) []*github.Organization); ok {
		r0 = rf(ctx, user, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Organization)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, *github.ListOptions) *github.Response); ok {
		r1 = rf(ctx, user, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, *github.ListOptions) error); ok {
		r2 = rf(ctx, user, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
