version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    labels:
      - semver:patch
      - type:dependency-upgrade
    groups:
      go-dependencies:
        update-types:
          - "minor"
          - "patch"
