github:
  username: ${{ secrets.IMPLEMENTATION_GITHUB_USERNAME }}
  token:    ${{ secrets.IMPLEMENTATION_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@buildpacks/platform-maintainers @buildpacks/toc"
