// Code generated by mockery v2.53.6. DO NOT EDIT.

package services

import (
	context "context"

	github "github.com/google/go-github/v89/github"
	mock "github.com/stretchr/testify/mock"
)

// MockIssuesService is an autogenerated mock type for the IssuesService type
type MockIssuesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, owner, repo, issue
func (_m *MockIssuesService) Create(ctx context.Context, owner string, repo string, issue *github.IssueRequest) (*github.Issue, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, issue)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *github.Issue
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *github.IssueRequest) (*github.Issue, *github.Response, error)); ok {
		return rf(ctx, owner, repo, issue)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *github.IssueRequest) *github.Issue); ok {
		r0 = rf(ctx, owner, repo, issue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *github.IssueRequest) *github.Response); ok {
		r1 = rf(ctx, owner, repo, issue)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, *github.IssueRequest) error); ok {
		r2 = rf(ctx, owner, repo, issue)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: ctx, owner, repo, number
func (_m *MockIssuesService) Get(ctx context.Context, owner string, repo string, number int) (*github.Issue, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, number)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *github.Issue
	var r1 *github.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (*github.Issue, *github.Response, error)); ok {
		return rf(ctx, owner, repo, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *github.Issue); ok {
		r0 = rf(ctx, owner, repo, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Issue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) *github.Response); ok {
		r1 = rf(ctx, owner, repo, number)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int) error); ok {
		r2 = rf(ctx, owner, repo, number)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewMockIssuesService creates a new instance of MockIssuesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuesService {
	mock := &MockIssuesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
