// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package services

import (
	context "context"

	github "github.com/google/go-github/v32/github"
	mock "github.com/stretchr/testify/mock"
)

// MockIssuesService is an autogenerated mock type for the IssuesService type
type MockIssuesService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, owner, repo, issue
func (_m *MockIssuesService) Create(ctx context.Context, owner string, repo string, issue *github.IssueRequest) (*github.Issue, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, issue)

	var r0 *github.Issue
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *github.IssueRequest) *github.Issue); ok {
		r0 = rf(ctx, owner, repo, issue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Issue)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, *github.IssueRequest) *github.Response); ok {
		r1 = rf(ctx, owner, repo, issue)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, *github.IssueRequest) error); ok {
		r2 = rf(ctx, owner, repo, issue)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Get provides a mock function with given fields: ctx, owner, repo, number
func (_m *MockIssuesService) Get(ctx context.Context, owner string, repo string, number int) (*github.Issue, *github.Response, error) {
	ret := _m.Called(ctx, owner, repo, number)

	var r0 *github.Issue
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) *github.Issue); ok {
		r0 = rf(ctx, owner, repo, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Issue)
		}
	}

	var r1 *github.Response
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) *github.Response); ok {
		r1 = rf(ctx, owner, repo, number)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*github.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, int) error); ok {
		r2 = rf(ctx, owner, repo, number)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
