// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	name "github.com/google/go-containerregistry/pkg/name"
	remote "github.com/google/go-containerregistry/pkg/v1/remote"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/google/go-containerregistry/pkg/v1"
)

// ImageFunction is an autogenerated mock type for the ImageFunction type
type ImageFunction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ImageFunction) Execute(_a0 name.Reference, _a1 ...remote.Option) (v1.Image, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 v1.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(name.Reference, ...remote.Option) (v1.Image, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(name.Reference, ...remote.Option) v1.Image); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(v1.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(name.Reference, ...remote.Option) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageFunction creates a new instance of ImageFunction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageFunction(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageFunction {
	mock := &ImageFunction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
