name:        'Setup pack CLI'
description: 'Setup the Cloud Native Buildpacks pack CLI as well as other useful tools and add them to $PATH'
author:      'Cloud Native Buildpacks'

inputs:
  crane-version:
    description: 'The version of crane to install'
    required:    false
    default:     '0.1.4'
  jq-version:
    description: 'The version of jq to install'
    required:    false
    default:     '1.6'
  pack-version:
    description: 'The version of pack to install'
    required:    false
    default:     '0.17.0'
  yj-version:
    description: 'The version of yj to install'
    required:    false
    default:     '5.0.0'

runs:
  using: "composite"
  steps:
  - name:  Setup pack CLI
    shell: bash
    run:   |
           #!/usr/bin/env bash

           set -euo pipefail

           mkdir -p "${HOME}"/bin
           echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"

           CRANE_VERSION=${{ inputs.crane-version }}
           echo "Installing crane ${CRANE_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             "https://github.com/google/go-containerregistry/releases/download/v${CRANE_VERSION}/go-containerregistry_Linux_x86_64.tar.gz" \
           | tar -C "${HOME}/bin" -xz crane

           JQ_VERSION=${{ inputs.jq-version }}
           echo "Installing jq ${JQ_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             --output "${HOME}/bin/jq" \
             "https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64"
           chmod +x "${HOME}"/bin/jq

           PACK_VERSION=${{ inputs.pack-version }}
           echo "Installing pack ${PACK_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
           | tar -C "${HOME}/bin" -xz pack

           YJ_VERSION=${{ inputs.yj-version }}
           echo "Installing yj ${YJ_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             --output "${HOME}/bin/yj" \
             "https://github.com/sclevine/yj/releases/download/v${YJ_VERSION}/yj-linux"
           chmod +x "${HOME}"/bin/yj
